using System.Windows;

namespace ClonarDC;

public partial class MainWindow
{
    private async void LinkDiscord_Click(object sender, RoutedEventArgs e)
    {
        var code = DiscordLinkCodeBox.Text.Trim().ToUpperInvariant();
        if (code.Length < 6)
        {
            DiscordLinkStatusText.Text = "Enter the one-time code generated by /link in the official GuildSync bot.";
            return;
        }

        LinkDiscordButton.IsEnabled = false;
        DiscordLinkStatusText.Text = "Connecting your Discord account…";
        try
        {
            using var timeout = new CancellationTokenSource(TimeSpan.FromSeconds(20));
            var result = await _auth.LinkDiscordAsync(_session, code, timeout.Token);
            DiscordLinkCodeBox.Text = string.Empty;
            DiscordLinkStatusText.Text = result.Linked
                ? $"Discord connected successfully. Account ID: {result.DiscordUserId}."
                : "The Discord account could not be connected.";
        }
        catch (OperationCanceledException)
        {
            DiscordLinkStatusText.Text = "The request took too long. Generate a new /link code and try again.";
        }
        catch (Exception ex)
        {
            DiscordLinkStatusText.Text = ex.Message;
        }
        finally
        {
            LinkDiscordButton.IsEnabled = true;
        }
    }
}